### PR TITLE
Improved Terms of Services section with some UI/Colour/Format changes

### PR DESCRIPTION
**Pull request by kituuu**

### CODE REVIEW

**Comment by kituuu** [comment]
Please review it and comment any issues, I will try to fix them ASAP.

**Comment by RIKI-05** [comment]
@kituuu 
hey can you please change the word food-n-food with momomia
and remove the last point of the terms and condition

**Comment by kituuu** [comment]
Sure Di :)

**Comment by kituuu** [comment]
Hey Di, I did it , but I don't know how to manage new commit with existing PR. So I don't know it is showing here or not. I will find it tomorrow morning.

**Comment by RIKI-05** [comment]
Hey just create a new PR

**Comment by RIKI-05** [comment]
@kituuu It's working fine accepted your PR :) happy hacking

**Comment by kituuu** [comment]
Thanks :D , for my life's first accepted PR

**Pull request merged**
