### PR TITLE
Added About Us Responsive Page

### PR DESCRIPTION
**Pull request by void1244**
Added an sample about us page. the page is fully responsive. you can easily make the image as a side by side grid, changing small css. i have entered the dummy data you can edit by your own. Thanks It was a great experience.
you can connect with me on my Github @B1TSH3LL.

### CODE REVIEW

**Comment by void1244** [comment]
Please add hacktoberfest and  hacktoberfest-accepted label to this PR.

**Comment by RIKI-05** [comment]
> Please add hacktoberfest and hacktoberfest-accepted label to this PR
You  have not done any changed accept changing the alignment of the index.html file

**Comment by B1TSH3LL** [comment]
Please check the code I haven't done alignment  407+ lines were added

**Comment by B1TSH3LL** [comment]
Please check the line 1032 - 1070 in index.html

**Comment by RIKI-05** [comment]
@B1TSH3LL there are 13 conflicts please try again

**Comment by void1244** [comment]
i had resolved the conflicts

**Comment by void1244** [comment]
is there anything else ???

**Comment by RIKI-05** [comment]
See the issue :( 
I can't merge your PR somethings not right with the CSS

**Pull request closed without merging**
