### PR TITLE
Created new contact us page :D

### PR DESCRIPTION
**Pull request by kituuu**
Create new good looking contact us page from scratch.
Added some animated icons.
Added animation in form.
100% Mobile responsive

Future ideas:
Replace form style with glass design.
Link address with google maps.
Change the headline xD

Any minor changes you want, comment, and I will change it.
Any major changes you want, I will do after 2 days with the new PR.

Kindly give Hacktoberfest tag :D
Image source : Unsplash (no copyright I think)
icons source :  icons8.com (I don't know about copyright, I asked you same thing on tg)

### CODE REVIEW

**Comment by RIKI-05** [comment]
@kituuu 
This looks Fantastic... 🎇 
Can you change **"Your Friends are Hungry :( Order now from MOMOMIA"** to **"We would love to hear from you!"**

Also please add the navbar and the footer the same as we have on our index page....that would be your next pr 😉

**Comment by kituuu** [comment]
Okie, i am changing the heading and footer... I tried the navbar yesterday but it was crashing, cause i messed up the css... I will try again today 🥲 this is my first web-dev project xD

**Comment by kituuu** [comment]
Same means with the black bg na? And momomia on left side etc etc

**Comment by kituuu** [comment]
Heading Done, Working on Footer and nav bar ... Give me some time 😅
Also if you have any different color combination ideas, you can tell Di.

**Comment by kituuu** [comment]
Riki Didi, Footer add kar diya hai maine ... Should I commit in this PR or should I create new one ?? And also one more thing that momo loading animation ... has some issues... I don't know why but it's stuck... Keeps on loading .... (maybe on my local system only) ... Will Settle Nav bar later ... Aaj DSA ka lecture dekhna hai ek 😅

**Comment by RIKI-05** [comment]
@kituuu you can commit the changes to this PR itself
 baki do things at your own pace 😄 

> Riki Didi, Footer add kar diya hai maine ... Should I commit in this PR or should I create new one ?? And also one more thing that momo loading animation ... has some issues... I don't know why but it's stuck... Keeps on loading .... (maybe on my local system only) ... Will Settle Nav bar later ... Aaj DSA ka lecture dekhna hai ek 😅

**Comment by kituuu** [comment]
Galti se doosri branch me commit ho gaya 😐 ... I am closing this PR ... Sorry

**Pull request closed without merging**
