### PR TITLE
Added About us page 

### PR DESCRIPTION
**Pull request by Coderner**
Screenshot (21)
Screenshot (22)

### CODE REVIEW

**Comment by RIKI-05** [comment]
@Coderner  the page is ok but can you plz stick to the font used in the current deployments

**Comment by Coderner** [comment]
Ok

**Comment by Coderner** [comment]
@RIKI-05 fonts changed please review now
Screenshot (24)

**Comment by RIKI-05** [comment]
@Coderner no dude it's the same

**Pull request merged**
