### PR TITLE
UI UX Changes

### PR DESCRIPTION
**Pull request by Morbius00**
# UI UX Changes
# Before
Screenshot 2022-10-09 200746
Screenshot 2022-10-09 200804

# After:
Screenshot 2022-10-09 195912
Screenshot 2022-10-09 195944
> Hope you like the new UI and dont forget to add the Hacktober Label before Merge

### CODE REVIEW

**Comment by RIKI-05** [comment]
@Morbius00 good job but


- please remove the chopstick momo plate image over the image is not looking good
- also the gradient navbar is not sticking to the theme make it black

**Comment by Morbius00** [comment]
> @Morbius00 good job but 
> 
> * please remove the chopstick momo plate image over the image is not looking good
> * also the gradient navbar is not sticking to the theme make it black
> * Issues with the padding and margin, where the flavour inebriates you is getting cut

should I put the logo insted of those chopsticks?
and the issue regarding * Issues with the padding and margin, where the flavour inebriates you is getting cut
I think you should need to decrease you screen zooming because in device its ok

**Comment by RIKI-05** [comment]
> > @Morbius00 good job but 
> > 
> > * please remove the chopstick momo plate image over the image is not looking good
> > * also the gradient navbar is not sticking to the theme make it black
> > * Issues with the padding and margin, where the flavour inebriates you is getting cut
> 
> should I put the logo insted of those chopsticks? and the issue regarding * Issues with the padding and margin, where the flavour inebriates you is getting cut I think you should need to decrease you screen zooming because in device its ok

Either remove the image or put the image with the background
I'll check once more

**Comment by Morbius00** [comment]
Screenshot 2022-10-09 202854

>The above changes you mentioned are sorted I hope!

**Comment by RIKI-05** [comment]
it has conflicts 
also, I asked you to remove the image when you already have an image in the background and to make the navbar black

**Comment by Morbius00** [comment]
This is not atleast tell to make the required changes but instead of that close the Pr...😞

**Pull request closed without merging**
