### PR TITLE
New contact page UI

### PR DESCRIPTION
**Pull request by amitroy-thedev**
Di i've been in trouble first i've commit mistakenly 3 times then deleted and now i finally added new pr with new branch then it resolve i guess but still there are two pr :(
I'm new to github so thora issue ho gya..

### CODE REVIEW

**Review by amitroy-thedev — COMMENTED** [review]
Left image was not loading so i uploaded and then edited the link

**Comment by RIKI-05** [comment]
@amitroy-thedev it's fine page looks good accepted the PR

**Comment by amitroy-thedev** [comment]
@RIKI-05 Thanks di

**Comment by amitroy-thedev** [comment]
@RIKI-05 
Di can i find bugs and then resolve it ..
i've seen that when we click momo categories it shows go to cart and when we click other two categories it show check out and also solve other problem here and there

**Comment by amitroy-thedev** [comment]
conflict
@RIKI-05 Di will you help me to solve this
I'm trying to sync code with your repo but this is showing will you please guide me

**Pull request merged**
