### PR TITLE
Added gif at left hand side of Navbar

### PR DESCRIPTION
**Pull request by codewithrabeeh**
image

Issue #64

### CODE REVIEW

**Comment by RIKI-05** [comment]
It's not working dude...

**Comment by RIKI-05** [comment]
hey insert the gif in the image folder and then link it may be then it'll work

**Comment by codewithrabeeh** [comment]
> hey insert the gif in the image folder and then link it may be then it'll work

I added it that way. Let me check again.

**Comment by codewithrabeeh** [comment]
@RIKI-05 Could you check again?

**Comment by RIKI-05** [comment]
@codewithrabeeh working fine

**Pull request merged**
